/* eslint-disable @next/next/no-img-element */
"use client";

import { useState } from "react";
import styles from "./page.module.css";

export default function Home() {
	const [isSubmitting, setIsSubmitting] = useState(false);
	const [error, setError] = useState<string | null>(null);

	return (
		<div className={styles.container}>
			<div className={styles.card}>
				<div className={styles.header}>
					<h1 className={styles.title}>NFL Calcutta Auction</h1>
					<p className={styles.subtitle}>Create a new auction event</p>
				</div>

				<form
					className={styles.form}
					onSubmit={async (e) => {
						e.preventDefault();
						if (isSubmitting) return;
						
						setIsSubmitting(true);
						setError(null);
						
						try {
							const form = e.target as HTMLFormElement;
							const data = new FormData(form);
						const eventName = (data.get("name") as string) || "NFL Calcutta Demo Event";
						const playersText = (data.get("players") as string) || "";
						
						// Parse players from textarea (one per line, optional @handle)
						const players = playersText
							.split("\n")
							.map((line) => line.trim())
							.filter(Boolean)
							.map((line) => {
								const match = line.match(/^(.+?)(?:\s+@(.+))?$/);
								if (match) {
									return {
										name: match[1].trim(),
										handle: match[2] ? `@${match[2].trim()}` : undefined,
									};
								}
								return { name: line };
							});

						// Default to demo players if none provided
						const finalPlayers = players.length > 0 
							? players 
							: [
								{ name: "Alice", handle: "@alice" },
								{ name: "Bob", handle: "@bob" },
								{ name: "Carol", handle: "@carol" },
								{ name: "Dave", handle: "@dave" },
							];

						// Convert dollars to cents for API
						const anteDollars = Number(data.get("anteDollars") || 10);
						const minIncrementDollars = Number(data.get("minIncrementDollars") || 1);

						const payload = {
							name: eventName,
							// rngSeed is now optional - will be auto-generated by the API
							ruleSet: {
								anteCents: Math.round(anteDollars * 100),
								minIncrementCents: Math.round(minIncrementDollars * 100),
								auctionTimerSeconds: Number(data.get("auctionTimerSeconds") || 30),
								antiSnipeExtensionSeconds: Number(
									data.get("antiSnipeExtensionSeconds") || 10,
								),
								roundAllocations: {
									wildcard: 0.1,
									divisional: 0.2,
									conference: 0.3,
									superbowl: 0.4,
								},
							},
							players: finalPlayers,
						};
							const response = await fetch("/api/events", {
								method: "POST",
								headers: { "content-type": "application/json" },
								body: JSON.stringify(payload),
							});

							const res = await response.json();
							
							if (!response.ok) {
								const errorMsg = res.error || "Failed to create event";
								const details = res.details ? `\n\nDetails: ${res.details}` : "";
								throw new Error(errorMsg + details);
							}

							if (res.eventId) {
								window.location.href = `/host/${res.eventId}`;
							} else {
								throw new Error("No event ID returned");
							}
						} catch (err) {
							console.error("Error creating event:", err);
							setError(err instanceof Error ? err.message : "Failed to create event");
							setIsSubmitting(false);
						}
					}}
				>
					<div className={styles.section}>
						<h2 className={styles.sectionTitle}>Event Settings</h2>
						<div className={styles.fieldsGrid}>
							<div className={styles.field}>
								<label htmlFor="name" className={styles.label}>
									Event Name
								</label>
								<input
									id="name"
									name="name"
									type="text"
									className={styles.input}
									placeholder="Super Bowl 2024"
									required
								/>
							</div>

							<div className={styles.field}>
								<label htmlFor="anteDollars" className={styles.label}>
									Ante
								</label>
								<input
									id="anteDollars"
									name="anteDollars"
									type="number"
									step="0.01"
									min="0"
									className={styles.input}
									placeholder="10.00"
									defaultValue="10"
								/>
								<span className={styles.helperText}>Entry fee per player in dollars</span>
							</div>

							<div className={styles.field}>
								<label htmlFor="minIncrementDollars" className={styles.label}>
									Minimum Increment
								</label>
								<input
									id="minIncrementDollars"
									name="minIncrementDollars"
									type="number"
									step="0.01"
									min="0"
									className={styles.input}
									placeholder="1.00"
									defaultValue="1"
								/>
								<span className={styles.helperText}>Minimum bid increase in dollars</span>
							</div>

							<div className={styles.field}>
								<label htmlFor="auctionTimerSeconds" className={styles.label}>
									Auction Timer
								</label>
								<input
									id="auctionTimerSeconds"
									name="auctionTimerSeconds"
									type="number"
									className={styles.input}
									placeholder="30"
									defaultValue="30"
								/>
								<span className={styles.helperText}>Countdown duration in seconds</span>
							</div>

							<div className={styles.field}>
								<label htmlFor="antiSnipeExtensionSeconds" className={styles.label}>
									Anti-Snipe Extension
								</label>
								<input
									id="antiSnipeExtensionSeconds"
									name="antiSnipeExtensionSeconds"
									type="number"
									className={styles.input}
									placeholder="10"
									defaultValue="10"
								/>
								<span className={styles.helperText}>Extension time when bid placed near end</span>
							</div>
						</div>
					</div>

					<div className={styles.section}>
						<h2 className={styles.sectionTitle}>Players</h2>
						<div className={styles.field}>
							<label htmlFor="players" className={styles.label}>
								Player List
							</label>
							<span className={styles.helperText}>
								One player per line. You can use @handles (e.g., "John @johnny")
							</span>
							<textarea
								id="players"
								name="players"
								className={styles.textarea}
								placeholder="Alice&#10;Bob @bob&#10;Carol @carol&#10;Dave"
							/>
						</div>
					</div>

					{error && (
						<div style={{ 
							padding: "12px", 
							background: "rgba(239, 68, 68, 0.1)", 
							border: "1px solid rgba(239, 68, 68, 0.3)",
							borderRadius: "8px",
							color: "#fca5a5",
							fontSize: "14px"
						}}>
							{error}
						</div>
					)}
					<div className={styles.actions}>
						<button 
							type="submit" 
							className={styles.button}
							disabled={isSubmitting}
						>
							{isSubmitting ? "Creating..." : "Create Event"}
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}
